# Generated by Django 2.2 on 2020-02-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200114_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_known',
            field=models.BooleanField(default=False),
        ),
    ]
