# Generated by Django 2.2 on 2020-02-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_known',
        ),
    ]
