# Generated by Django 2.2 on 2019-12-23 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
