# Generated by Django 2.2 on 2019-12-23 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('parent_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Deck')),
            ],
        ),
    ]
