# Generated by Django 2.2 on 2019-12-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20191223_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
