# Generated by Django 2.2 on 2019-12-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20191223_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
