# Generated by Django 2.2 on 2019-12-29 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0007_auto_20191227_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
