# Generated by Django 2.2 on 2019-12-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20191229_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='parent_deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Deck'),
        ),
    ]
