# Generated by Django 2.2 on 2020-02-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20191229_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_known',
            field=models.BooleanField(default=False),
        ),
    ]
