# Generated by Django 2.2 on 2020-02-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_is_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_known',
        ),
    ]
