# Generated by Django 2.2 on 2020-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_remove_card_is_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_known',
            field=models.BooleanField(default=False),
        ),
    ]
