# Generated by Django 2.2 on 2020-02-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_card_is_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_known',
        ),
    ]
